[package]
authors = ["Kevin K. <kbknapp@gmail.com>"]
description = "Cargo subcommand for displaying when dependencies are out of date"
exclude = ["*.png"]
keywords = ["cargo", "subcommand", "dependencies", "cargo-subcommand", "deps"]
license = "MIT"
name = "cargo-outdated"
readme = "README.md"
repository = "https://github.com/kbknapp/cargo-outdated.git"
version = "0.4.0"
[[bin]]
name = "cargo-outdated"

[dependencies]
cargo = "0.20.0"
clap = "2.26.0"
env_logger = "0.4.3"
semver = "0.7.0"
serde = "1.0.11"
serde_derive = "1.0.11"
tabwriter = "~1.0.3"
tempdir = "~0.3.5"
toml = "~0.4.3"

[features]
debug = []
default = []
[profile.release]
lto = true
